# Generated by Django 4.1.7 on 2023-03-25 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dbconnection', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CarModels',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('carname', models.CharField(max_length=100)),
                ('carmodel', models.CharField(max_length=50)),
                ('price', models.BigIntegerField()),
                ('image', models.ImageField(upload_to='images/')),
            ],
            options={
                'db_table': 'car_models',
            },
        ),
    ]
