# Generated by Django 4.1.7 on 2023-04-02 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dbconnection', '0003_admin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carmodels',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
