# Generated by Django 4.1.7 on 2023-05-06 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dbconnection', '0005_carbooking'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=50, unique=True)),
                ('user', models.CharField(default=False, max_length=50, unique=True)),
                ('message', models.TextField()),
            ],
            options={
                'db_table': 'contact_table',
            },
        ),
    ]
