# Generated by Django 4.1.7 on 2023-04-02 00:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registrationmodule', '0002_admin'),
    ]

    operations = [
        migrations.RenameField(
            model_name='admin',
            old_name='username',
            new_name='email',
        ),
    ]
