# Generated by Django 4.1.7 on 2023-04-02 01:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registrationmodule', '0003_rename_username_admin_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carmodels',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
