# Generated by Django 4.1.7 on 2023-05-04 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registrationmodule', '0005_carbooking'),
    ]

    operations = [
        migrations.AddField(
            model_name='carbooking',
            name='noofdays',
            field=models.BigIntegerField(default=False),
        ),
    ]
