# Generated by Django 4.1.7 on 2023-05-04 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registrationmodule', '0007_remove_carbooking_noofdays_carbooking_pickuptime_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carbooking',
            name='pickuptime',
            field=models.CharField(default=False, max_length=50),
        ),
    ]
