# Generated by Django 4.1.7 on 2023-05-06 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registrationmodule', '0008_alter_carbooking_pickuptime'),
    ]

    operations = [
        migrations.AddField(
            model_name='carbooking',
            name='tprice',
            field=models.BigIntegerField(default=None),
        ),
    ]
